# Generated by Django 5.2.6 on 2025-09-23 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand_name', models.CharField(max_length=20)),
                ('Price_rate', models.IntegerField()),
                ('Engine_type', models.CharField(max_length=20)),
                ('Car_color', models.CharField(max_length=20)),
                ('Manufacture_year', models.IntegerField()),
            ],
        ),
    ]
